import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Font files can be colocated inside of `app`
const Geist = localFont({
  src: [ { path: "../assets/fonts/Geist-Medium.woff2", weight: "500" }, { path: "../assets/fonts/Geist-SemiBold.woff2", weight: "600" }, { path: "../assets/fonts/Geist-Bold.woff2", weight: "700" }, { path: "../assets/fonts/Geist-Regular.woff2", weight: "400" }],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={Geist.className}>{children}</body>
    </html>
  );
}
